name: program
version: 0.0.1
ghc-options: -Wall -Werror
executable:
  main: Main.hs
  source-dirs: src
  dependencies:
    - base
    - binary
    - containers
    - directory
    - distributed-process
    - lens
    - mtl
    - network-transport-tcp
    - network-transport
    - non-empty
    - random
    - semigroups
    - text
    - time
    - validation
